language: node_js
node_js:
  - "8"
script:
  - npm install
  - npm run testCI
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
branches:
  only:
    - master
